### ISSUE TITLE
OpenAdaptxt SDK

### ISSUE THREAD

**Issue by ghost** [k3a/OctopusKeyboard#1]
Hi,
I have developed a Keyboard for iOS 8 and it's on the App Store. I am planning to add predictive text to it. Since OpenAdaptxt supports Persian and it seems that you have used their library to make your tweak, I wanted to ask you a question.
I believe OpenAdaptxt library is in Java. How can I port that to Xcode and iOS?
Your help would be highly appreciated.

**Comment by k3a** [comment]
Hi,
openadaptxt is written in c++. It just have Java bindings because originally it was used for Java keyboard on Android.

I just put all librarty sources in one big xcode static library project and compiled it. It was pretty straightforward. I don't remember but maybe there also was some xcode project prepared (for mac maybe) but if not, you can always make it and put sources inside.

Download their complete svn repo and explore. 

Examples of C api are here:
http://openadaptxt.svn.sourceforge.net/viewvc/openadaptxt/Trunk/api/docs/examples/ 

Ypu may find my octopus class as a good starting point for using their api: 
https://github.com/k3a/OctopusKeyboard/blob/master/octopuscore/OctopusDaemon/TextInput.mm

Hope it helps. Let me know if you need more help. I can try to checkout from svn myself and try to prepare those xcode project again to describe the process in more details.

Also let me know once your keyboard is released on the appstore. :)

**Comment by ghost** [comment]
Hi,
Thank you for your prompt reply. I need to say I'm fairly new to development! 
I've already developed a simple Persian keyboard which does practically nothing other than typing and changing colors! (Although this level of work has been praised by many because iOS doesn't support Persian by default) It's called FarsTap and it's been live on the App Store since iOS 8 debut.
I've checked the Java documentation for OpenAdaptxt and it seemed rather easy to implement. But the C APIs look rather difficult to understand and read.
I understand that you may be busy but could you please help me in a way I can find out what I should do? I wish I could have some Objective-C wrappers from which I could call relevant methods and so on!

Saeed

**Comment by k3a** [comment]
Hi. OTextInputSystem from https://github.com/k3a/OctopusKeyboard/blob/master/octopuscore/OctopusDaemon/TextInput.mm is my C++ class which wraps their C api in some more understandable way. It should help you a lot. There are potentially some Unicode problems and problems with key proximity (keyboard layouts) but those are not major problems so that class should be pretty usable.

**Comment by ghost** [comment]
Thank you so much.
I’ll try to make it work.

Thanks again
Saeed

**Comment by cyrilzakka** [comment]
Hey, did you ever get it working? I'm trying my hand at it now

**Comment by k3a** [comment]
OpenAdaptxt is open-source (http://openadaptxt.sourceforge.net/) and you should be able to compile it as I was. I haven't done anything magical, no modifications to the code, just setting correct arch in the xcode project files. At that time there were no arm64 arch on iOS, though. 

If you encounter some problems with arm64 (as I heard some report from [Crimson Keyboard](https://crimsonkeyboard.com/) developer), you may have to contribute to the open-source code or purchase their paid license. You can contact them [http://www.adaptxt.com/contact/](here) and ask for pricing and conditions. 

Closing the issue.
